import Foundation

struct RoastProvider {
    func roast(for zone: ComfortZone) -> String {
        bank(for: zone).randomElement() ?? ""
    }
}

private extension RoastProvider {
    func bank(for zone: ComfortZone) -> [String] {
        switch zone {
        case .comfortable: Self.comfortable
        case .stretching: Self.stretching
        case .unhinged: Self.unhinged
        }
    }

    static let comfortable = [
        "Look at you, financially responsible. Disgusting.",
        "Your accountant would be proud. Your group chat, less so.",
        "This is the budgeting equivalent of going to bed at 9pm.",
        "Safe. Boring. Sustainable. Who even are you?",
        "You could buy this and still sleep at night. Lame.",
        "Certified adult behavior detected.",
        "No risk, no debt, no fun.",
        "You're basically a spreadsheet with a pulse.",
        "Even your future self can't complain about this one.",
        "This won't make the algorithm. Try harder.",
        "Responsible to the point of being a little smug, honestly.",
        "Your savings account didn't even flinch.",
        "The most rebellious thing here is the font.",
        "You read the terms and conditions, didn't you.",
        "This purchase has a bedtime.",
        "Your emergency fund didn't even wake up.",
        "Congrats, you've unlocked: nothing exciting.",
        "The vibe is 'brings a reusable bag to the mall.'",
        "Financially, you're wearing a helmet indoors.",
        "Warren Buffett just nodded slightly.",
        "This decision files its taxes early.",
        "You could return it and nothing would happen. Thrilling.",
        "Boringly within your means. Chef's kiss, unfortunately.",
        "This is what peace of mind costs, apparently. Cheap.",
        "Your portfolio yawned.",
        "This is the financial equivalent of decaf.",
        "You've been pre-approved for being boring.",
        "Not a single sleepless night in sight. Coward.",
        "The riskiest part was walking to checkout.",
        "Your budget didn't even change its facial expression.",
        "This is fine. Genuinely, upsettingly fine.",
        "Somewhere a financial planner shed a single proud tear.",
        "You brought a coupon, didn't you.",
        "This won't be a story anyone tells at parties.",
        "The math checked out on the first try, nerd.",
        "Your wallet didn't even open all the way.",
        "This is a purchase you'd tell your grandma about.",
    ]

    static let stretching = [
        "Doable, if you skip lunch. Every lunch. Forever.",
        "Your budget just took a deep breath in.",
        "This is a 'check the account before you tap' purchase.",
        "Living on the edge, but the edge still has a railing.",
        "You'll afford it and quietly panic. That's the vibe.",
        "One surprise bill away from regret.",
        "The math works. Your nervous system, less so.",
        "This is a 'don't tell anyone what it cost' situation.",
        "You can swing it. You'll just feel the swing.",
        "Bold. Slightly sweaty, but bold.",
        "Your rent is watching this decision very closely.",
        "Affordable the way a parachute is optional.",
        "You'll afford it. Your weekend plans won't.",
        "Your savings and you are now in a long-distance relationship.",
        "Green light, yellow stomach.",
        "Technically fine. Emotionally a group project.",
        "Your budget is doing yoga to make this fit.",
        "It fits, like jeans after Thanksgiving.",
        "You'll feel this one in your molars.",
        "The receipt is going straight to the shredder.",
        "Doable if the universe cooperates. It won't.",
        "You're negotiating with yourself and losing.",
        "Half confidence, half indigestion.",
        "Send it, but keep the box just in case.",
        "You'll afford it and immediately Google side hustles.",
        "This is a 'set the payment reminder' kind of buy.",
        "Your budget is holding its breath and turning colors.",
        "One 'treat yourself' too far, but only slightly.",
        "You can do this. Just don't also do groceries.",
        "The confidence is there. The cushion is not.",
        "You'll feel rich for exactly one afternoon.",
        "Sweating, but make it aspirational.",
        "Your savings account left you on delivered.",
        "You'll afford it and think about it at 3am.",
        "Risky click of the week, honestly.",
        "The vibe is 'brave face at the register.'",
        "Fine, but cancel the trip you were planning.",
    ]

    static let unhinged = [
        "This isn't a budget, it's a cry for help.",
        "Bankruptcy has entered the chat.",
        "Your bank just scheduled a wellness check.",
        "Sending it like rent is a rumor.",
        "Financial advisors are gathering outside your home.",
        "This is how cautionary tales begin.",
        "You don't afford this. You survive it.",
        "The number went up. Your odds went down.",
        "Delusion has never looked this expensive.",
        "Future you is already filing the complaint.",
        "We did the math. The math is screaming.",
        "Buy it. Therapy is also a purchase.",
        "This is arson, but for your bank account.",
        "The decimal point is begging you to stop.",
        "You're not buying it, you're adopting a liability.",
        "Your credit score just left on read.",
        "Somewhere, a calculator is on fire.",
        "This is a hostage situation and you're the money.",
        "Rent? Never heard of her.",
        "Your future is now a GoFundMe.",
        "The bank called it brave. That's not a compliment.",
        "Economists are studying you as a warning.",
        "This is generational wealth, going backwards.",
        "You'll be famous. In a case study.",
        "This is financial parkour with no landing mat.",
        "Your bank added you to a watchlist. A sad one.",
        "You've reinvented poverty as a lifestyle choice.",
        "This purchase needs a warning label and a lawyer.",
        "The number has a body count now.",
        "You're speedrunning ruin. World record pace.",
        "Even the loan shark said maybe don't.",
        "This is a decision your ancestors can feel.",
        "Congrats, you're the reason budgets exist.",
        "Your money left without saying goodbye.",
        "This is less 'purchase' and more 'event horizon.'",
        "The receipt should come with grief counseling.",
        "This is how legends go broke.",
    ]
}
